"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /table_list/ HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /table_list/ HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
"GET /managebookings/ HTTP/1.1" 500 59
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
The joined path (/css/booking_list.css) is located outside of the base path component (/workspace/Afrik-kitchen/static)
Internal Server Error: /managebookings/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/Afrik-kitchen/booking/views.py", line 174, in managebooking
    return render(request, 'managebookings.html', context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: managebookings.html
"GET /managebookings/ HTTP/1.1" 500 5745
Internal Server Error: /managebookings/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/Afrik-kitchen/booking/views.py", line 174, in managebooking
    return render(request, 'managebookings.html', context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: managebookings.html
"GET /managebookings/ HTTP/1.1" 500 5745
Internal Server Error: /managebookings/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/Afrik-kitchen/booking/views.py", line 174, in managebooking
    return render(request, 'managebookings.html', context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: managebookings.html
"GET /managebookings/ HTTP/1.1" 500 5745
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io'. You may need to add '8000-ujuadimorad-afrikkitche-zqva385bw5d.ws-eu105.gitpod.io' to ALLOWED_HOSTS.
Internal Server Error: /managebookings/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/Afrik-kitchen/booking/views.py", line 174, in managebooking
    return render(request, 'managebookings.html', context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: managebookings.html
"GET /managebookings/ HTTP/1.1" 500 93886
Internal Server Error: /managebookings/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/Afrik-kitchen/booking/views.py", line 174, in managebooking
    return render(request, 'managebookings.html', context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: managebookings.html
"GET /managebookings/ HTTP/1.1" 500 93897
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_booking.html
"POST /create/ HTTP/1.1" 500 91510
Internal Server Error: /edit/65/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: booking_edit.html
"GET /edit/65/ HTTP/1.1" 500 90767
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: create_booking.html
"POST /create/ HTTP/1.1" 500 91510
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 1375, in url
    viewname = parser.compile_filter(bits[1])
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'create_booking'' from 'booking:'create_booking''
"POST /create/ HTTP/1.1" 500 170777
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 1375, in url
    viewname = parser.compile_filter(bits[1])
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'create_booking'' from 'booking:'create_booking''
"POST /create/ HTTP/1.1" 500 170777
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 1375, in url
    viewname = parser.compile_filter(bits[1])
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'create_booking'' from 'booking:'create_booking''
"POST /create/ HTTP/1.1" 500 170777
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 1375, in url
    viewname = parser.compile_filter(bits[1])
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'create_booking'' from 'booking:'create_booking''
"POST /create/ HTTP/1.1" 500 170777
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 1375, in url
    viewname = parser.compile_filter(bits[1])
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'create_booking'' from 'booking:'create_booking''
"POST /create/ HTTP/1.1" 500 170905
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_booking' not found. 'create_booking' is not a valid view function or pattern name.
"POST /create/ HTTP/1.1" 500 165663
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_booking' not found. 'create_booking' is not a valid view function or pattern name.
"POST /create/ HTTP/1.1" 500 165663
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_booking' not found. 'create_booking' is not a valid view function or pattern name.
"POST /create/ HTTP/1.1" 500 165663
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_booking' not found. 'create_booking' is not a valid view function or pattern name.
"POST /create/ HTTP/1.1" 500 165791
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create_booking' not found. 'create_booking' is not a valid view function or pattern name.
"POST /create/ HTTP/1.1" 500 165663
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/workspace/Afrik-kitchen/booking/views.py", line 90, in form_valid
    capacity = data['capacity']
KeyError: 'capacity'
"POST /create/ HTTP/1.1" 500 90082
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/workspace/Afrik-kitchen/booking/views.py", line 90, in form_valid
    capacity = data['capacity']
KeyError: 'capacity'
"POST /create/ HTTP/1.1" 500 90082
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/workspace/Afrik-kitchen/booking/views.py", line 90, in form_valid
    capacity = data['capacity']
KeyError: 'capacity'
"POST /create/ HTTP/1.1" 500 90090
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/workspace/Afrik-kitchen/booking/views.py", line 90, in form_valid
    capacity = data['capacity']
KeyError: 'capacity'
"POST /create/ HTTP/1.1" 500 90090
Internal Server Error: /create/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/workspace/Afrik-kitchen/booking/views.py", line 90, in form_valid
    capacity = data['capacity']
KeyError: 'capacity'
"POST /create/ HTTP/1.1" 500 90090
Internal Server Error: /edit/65/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: booking_edit.html
"GET /edit/65/ HTTP/1.1" 500 90767
